## Лабораторная робата №3

In [121]:
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import os
import ipykernel
from sklearn.cluster import DBSCAN
from scipy.cluster.hierarchy import dendrogram, linkage, fcluster

In [122]:
os.chdir("C:/Users/вячеслав/Desktop/Lect_04/")

In [123]:
df = pd.read_csv("Econom_Cities_data.csv", delimiter = ';', decimal = ',', index_col='City')

In [124]:
df.head()

Work  Price  Salary
City                          
Amsterdam  1714   65.6    49.0
Athens     1792   53.8    30.4
Bogota     2152   37.9    11.5
Bombay     2052   30.3     5.3
Brussels   1708   73.8    50.5

In [125]:
print(df)

                Work  Price  Salary
City                               
Amsterdam       1714   65.6    49.0
Athens          1792   53.8    30.4
Bogota          2152   37.9    11.5
Bombay          2052   30.3     5.3
Brussels        1708   73.8    50.5
Buenos_Aires    1971   56.1    12.5
Cairo          -9999   37.1 -9999.0
Caracas         2041   61.0    10.9
Chicago         1924   73.9    61.9
Copenhagen      1717   91.3    62.9
Dublin          1759   76.0    41.4
Dusseldorf      1693   78.5    60.2
Frankfurt       1650   74.5    60.4
Geneva          1880   95.9    90.3
Helsinki        1667  113.6    66.6
Hong_Kong       2375   63.8    27.8
Houston         1978   71.9    46.3
Jakarta        -9999   43.6 -9999.0
Johannesburg    1945   51.1    24.0
Kuala_Lumpur    2167   43.5     9.9
Lagos           1786   45.2     2.7
Lisbon          1742   56.2    18.8
London          1737   84.2    46.2
Los_Angeles     2068   79.8    65.2
Luxembourg      1768   71.1    71.1
Madrid          1710   93.8 

Заметим, что Джакарта и Каир имееют странные показатели в 1-м и 3-м столбце, которые существенно отличаются от остальных, следовательно это выбросы и перед тем как построить дендограмму удалим их.  

In [126]:
#Процесс удаления
df = df.drop('Jakarta')
df = df.drop('Cairo')

In [127]:
print(df)

                Work  Price  Salary
City                               
Amsterdam       1714   65.6    49.0
Athens          1792   53.8    30.4
Bogota          2152   37.9    11.5
Bombay          2052   30.3     5.3
Brussels        1708   73.8    50.5
Buenos_Aires    1971   56.1    12.5
Caracas         2041   61.0    10.9
Chicago         1924   73.9    61.9
Copenhagen      1717   91.3    62.9
Dublin          1759   76.0    41.4
Dusseldorf      1693   78.5    60.2
Frankfurt       1650   74.5    60.4
Geneva          1880   95.9    90.3
Helsinki        1667  113.6    66.6
Hong_Kong       2375   63.8    27.8
Houston         1978   71.9    46.3
Johannesburg    1945   51.1    24.0
Kuala_Lumpur    2167   43.5     9.9
Lagos           1786   45.2     2.7
Lisbon          1742   56.2    18.8
London          1737   84.2    46.2
Los_Angeles     2068   79.8    65.2
Luxembourg      1768   71.1    71.1
Madrid          1710   93.8    50.0
Manila          2268   40.0     4.0
Mexico_City     1944   49.8 

Заметим, что нам надо провести стандартизацию данных. 

In [128]:
#Стандартизируем данные 
from sklearn import preprocessing
standart = preprocessing.StandardScaler()
standart.fit(df)
df_s = standart.transform(df)
df_s = pd.DataFrame(df_s, index = df.index, columns = df.columns)
df_s.head()

Work     Price    Salary
City                                   
Amsterdam -0.962166 -0.212712  0.386095
Athens    -0.509827 -0.770489 -0.373488
Bogota     1.577891 -1.522069 -1.145323
Bombay     0.997969 -1.881316 -1.398517
Brussels  -0.996961  0.174896  0.447351

Начнем разбиение нашего датасета на кластеры с помощью метода *DBSCAN*. Для этого нам надо подобрать значения *eps* и *m*. 

In [155]:
dbscan_1 = DBSCAN(eps = 0.8, metric = 'euclidean', min_samples = 3)

dbscan_1.fit(df_s)

dbscan_1.labels_

array([ 0,  1, -1, -1,  0,  2,  2,  0,  0,  0,  0,  0, -1, -1, -1, -1,  2,
       -1, -1, -1,  0, -1, -1,  0, -1,  2,  0,  0,  2,  0,  1, -1, -1,  0,
       -1, -1,  1,  2, -1,  0, -1,  2, -1,  0,  0, -1], dtype=int64)

In [131]:
unique, counts = np.unique(dbscan_1.labels_, return_counts=True)
print(np.asarray((unique, counts)).T)

[[-1 23]
 [ 0 14]
 [ 1  3]
 [ 2  6]]


После долгих и мучительных подборов, наилучший результат получился при следующих значениях *eps* и *m*, а именно:

In [159]:
dbscan_1 = DBSCAN(eps=0.81, metric='euclidean', min_samples=2)
dbscan_1.fit(df_s)
unique, counts = np.unique(dbscan_1.labels_, return_counts=True)
print(np.asarray((unique, counts)).T)

[[-1 10]
 [ 0 16]
 [ 1  3]
 [ 2  2]
 [ 3  7]
 [ 4  2]
 [ 5  2]
 [ 6  2]
 [ 7  2]]


In [160]:
df_s['dbscan_1'] = dbscan_1.labels_

Посмотрим на разбиение городов по кластерам. 

In [161]:
df_s['dbscan_1'].sort_values()

City
Luxembourg       -1
Tokyo            -1
Bombay           -1
Taipei           -1
Houston          -1
Stockholm        -1
Hong_Kong        -1
Panama           -1
Los_Angeles      -1
Manila           -1
Vienna            0
Madrid            0
New_York          0
Montreal          0
Paris             0
Sydney            0
Toronto           0
Milan             0
London            0
Amsterdam         0
Copenhagen        0
Frankfurt         0
Dusseldorf        0
Dublin            0
Chicago           0
Brussels          0
Athens            1
Seoul             1
Nicosia           1
Kuala_Lumpur      2
Bogota            2
Caracas           3
Buenos_Aires      3
Nairobi           3
Mexico_City       3
Johannesburg      3
Tel_Aviv          3
Singpore          3
Zurich            4
Geneva            4
Oslo              5
Helsinki          5
Rio_de_Janeiro    6
Lagos             6
Lisbon            7
San_Paulo         7
Name: dbscan_1, dtype: int64

Заметим, что мы нам не удалось избавиться от выбросов, 
опишем получившиеся кластеры:
- -1) Города развитых капиталистических стран, с достаточно большим уровнем безработицы, судя по большому числу часов работы и средней или ниже, чем средней, зарплатой
- 0) Города с уровнем жизни выше среднего
- 1) Города зависимых капиталистических стран с уровнем жизни около среднего
- 2) Города с дешевой рабочей силой и с низким уровнем жизни, скорее всего это города, в которых расположено много предприятий крупных компаний развитых капиталистических стран, использующих дешевый труд
- 3) Города с низкой зарплатой и средней или чуть выше средней стоймостью на жилье, скорее всего это города с высоким социальным неравенством
- 4) Города Швейцари
- 5) Города Скандинавских стран с развитой социальной структурой 
- 6) Города с высоким числом часов работ, с очень низкими зарпалатами и с высокой, относительно зарплат, стоймостию жизни
- 7) Города с высоким числом часов работ, с очень низкими зарпалатами и с высокой, относительно зарплат, стоймостию жизни


Оказалось, что при таком разбиение на кластеры, у нас города из кластеров 6 и 7 должны находится в одном кластере. Объединим эти кластеры. 

In [163]:
#Объединям эти кластеры 
for i in range(44):
    if (df_s['dbscan_1'][i] == 7):
        df_s['dbscan_1'][i] = 6

Теперь можем привести окончательное распределение городов по кластерам и описание получившихся кластеров.

In [165]:
df_s['dbscan_1'].sort_values()

City
Luxembourg       -1
Tokyo            -1
Bombay           -1
Taipei           -1
Houston          -1
Stockholm        -1
Hong_Kong        -1
Panama           -1
Los_Angeles      -1
Manila           -1
Vienna            0
Madrid            0
New_York          0
Montreal          0
Paris             0
Sydney            0
Toronto           0
Milan             0
London            0
Amsterdam         0
Copenhagen        0
Frankfurt         0
Dusseldorf        0
Dublin            0
Chicago           0
Brussels          0
Athens            1
Seoul             1
Nicosia           1
Kuala_Lumpur      2
Bogota            2
Caracas           3
Buenos_Aires      3
Nairobi           3
Mexico_City       3
Johannesburg      3
Tel_Aviv          3
Singpore          3
Zurich            4
Geneva            4
Oslo              5
Helsinki          5
Rio_de_Janeiro    6
Lisbon            6
San_Paulo         6
Lagos             6
Name: dbscan_1, dtype: int64

Описание кластеров:
- -1) Города развитых капиталистических стран, с достаточно большим уровнем безработицы, судя по большому числу часов работы и средней или ниже, чем средней зарплатой
- 0) Города с уровнем жизни выше среднего
- 1) Города зависимых капиталистических стран с уровнем жизни около среднего
- 2) Города с дешевой рабочей силой и с низким уровнем жизни, скорее всего это города, в которых расположено много предприятий крупных компаний развитых капиталистических стран, использующих дешевый труд
- 3) Города с низкой зарплатой и средней или чуть выше средней стоймостью на жилье, скорее всего это города с высоким социальным неравенством
- 4) Города Швейцари
- 5) Города Скандинавских стран с развитой социальной структурой 
- 6) Города с высоким числом часов работ, с очень низкими зарпалатами и с высокой, относительно зарплат, стоймостию жизни

Заметим, что получившиеся разбиние похоже на разбиения получившиеся с помощью иерархического анализа и метода *k-means*. Но стоит заметить, что оно успает предыдущим разбиениям, также были сложности с подбором подходящих значений *eps* и *m*, видимо метод *DBSCAN* не очень подходит для данного датасета. 